# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170111_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
