# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=140, unique=True),
        ),
    ]
